import { NextRequest, NextResponse } from 'next/server';
import dbConnect from '@/lib/mongodb';
import Category from '@/models/Category';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/app/api/auth/[...nextauth]/route'; // Adjust path as needed

export async function POST(req: NextRequest) {
  // const session = await getServerSession(authOptions);
  // if (!session || session.user?.role !== 'admin') {
  //   return NextResponse.json({ message: 'Unauthorized' }, { status: 401 });
  // }

  await dbConnect();
  try {
    const body = await req.json();
    // Basic validation
    if (!body.name) {
      return NextResponse.json({ message: 'Category name is required' }, { status: 400 });
    }
    // Slug can be auto-generated by Mongoose pre-save hook if not provided
    const category = new Category(body);
    await category.save();
    return NextResponse.json(category, { status: 201 });
  } catch (error: any) {
    console.error('Error creating category:', error);
    if (error.code === 11000) { // Duplicate key error (likely for slug)
        return NextResponse.json({ message: 'Category with this name or slug already exists.' }, { status: 409 });
    }
    return NextResponse.json({ message: 'Error creating category', error: error.message }, { status: 500 });
  }
}

export async function GET() {
  await dbConnect();
  try {
    const categories = await Category.find({}).sort({ name: 1 });
    return NextResponse.json(categories);
  } catch (error: any) {
    console.error('Error fetching categories:', error);
    return NextResponse.json({ message: 'Error fetching categories', error: error.message }, { status: 500 });
  }
}
