import React from 'react';
import { ButtonWidget } from '@/types/page-structure';

interface ButtonWidgetComponentProps {
  widget: ButtonWidget;
}

const ButtonWidgetComponent: React.FC<ButtonWidgetComponentProps> = ({ widget }) => {
  const { text, variant, colorScheme, size, href } = widget.properties;

  // Map props to Tailwind classes
  // This is a basic mapping, can be expanded or made more sophisticated
  const baseClasses = "font-semibold focus:outline-none focus:ring-2 focus:ring-opacity-50 rounded transition-colors duration-150";

  const sizeClasses = {
    xs: "px-2.5 py-1.5 text-xs",
    sm: "px-3 py-2 text-sm",
    md: "px-4 py-2 text-base",
    lg: "px-6 py-3 text-lg",
  };

  // Simplified color scheme to Tailwind - could be more comprehensive
  // Assumes colorScheme is like 'blue', 'green', 'red', 'gray'
  const variantClasses = {
    solid: `bg-${colorScheme}-600 hover:bg-${colorScheme}-700 text-white focus:ring-${colorScheme}-500`,
    outline: `border border-${colorScheme}-500 text-${colorScheme}-600 hover:bg-${colorScheme}-50 focus:ring-${colorScheme}-400`,
    ghost: `hover:bg-${colorScheme}-100 text-${colorScheme}-600 focus:ring-${colorScheme}-400`,
    link: `text-${colorScheme}-600 hover:text-${colorScheme}-700 underline focus:ring-${colorScheme}-400`,
  };

  // Fallback for colorScheme if a class is not generated by Tailwind JIT
  const defaultSolidClasses = `bg-gray-600 hover:bg-gray-700 text-white focus:ring-gray-500`;
  const defaultOutlineClasses = `border border-gray-500 text-gray-600 hover:bg-gray-50 focus:ring-gray-400`;
  const defaultGhostClasses = `hover:bg-gray-100 text-gray-600 focus:ring-gray-400`;
  const defaultLinkClasses = `text-gray-600 hover:text-gray-700 underline focus:ring-gray-400`;

  let currentVariantClasses = variantClasses[variant] || defaultSolidClasses;
  if (variant === 'outline' && !variantClasses[variant]) currentVariantClasses = defaultOutlineClasses;
  if (variant === 'ghost' && !variantClasses[variant]) currentVariantClasses = defaultGhostClasses;
  if (variant === 'link' && !variantClasses[variant]) currentVariantClasses = defaultLinkClasses;


  const combinedClasses = [
    baseClasses,
    sizeClasses[size] || sizeClasses.md,
    currentVariantClasses,
  ].join(' ');

  const content = text || 'Button';

  if (href) {
    return (
      <div className="p-1 flex"> {/* Added flex for inline-block like behavior if needed */}
        <a
          href={href}
          className={combinedClasses}
          target={href.startsWith('http') ? '_blank' : undefined}
          rel={href.startsWith('http') ? 'noopener noreferrer' : undefined}
        >
          {content}
        </a>
      </div>
    );
  }

  return (
    <div className="p-1 flex">
      <button type="button" className={combinedClasses}>
        {content}
      </button>
    </div>
  );
};

export default ButtonWidgetComponent;
