import { NextRequest, NextResponse } from 'next/server';
import dbConnect from '@/lib/mongodb';
import Article from '@/models/Article';
import User from '@/models/User'; // Needed to validate author
import Category from '@/models/Category'; // Needed to validate category
import Tag from '@/models/Tag'; // Needed to validate tags
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';

// POST: Create a new article
export async function POST(req: NextRequest) {
  // const session = await getServerSession(authOptions);
  // if (!session || !['admin', 'editor', 'author'].includes(session.user?.role || '')) {
  //   return NextResponse.json({ message: 'Unauthorized' }, { status: 401 });
  // }

  await dbConnect();
  try {
    const body = await req.json();

    // Basic validation
    if (!body.title || !body.content || !body.author) {
      return NextResponse.json({ message: 'Missing required fields: title, content, author' }, { status: 400 });
    }

    // Validate author exists
    const authorExists = await User.findById(body.author);
    if (!authorExists) {
      return NextResponse.json({ message: 'Author not found' }, { status: 400 });
    }

    // Validate category if provided
    if (body.category) {
      const categoryExists = await Category.findById(body.category);
      if (!categoryExists) {
        return NextResponse.json({ message: 'Category not found' }, { status: 400 });
      }
    }

    // Validate tags if provided
    if (body.tags && body.tags.length > 0) {
      const tagsExist = await Tag.find({ _id: { $in: body.tags } });
      if (tagsExist.length !== body.tags.length) {
        return NextResponse.json({ message: 'One or more tags not found' }, { status: 400 });
      }
    }

    // Slug can be auto-generated by Mongoose pre-save hook if not provided
    // Or if you want to ensure it here:
    // if (!body.slug) {
    //   body.slug = body.title.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]+/g, '');
    // }

    const article = new Article(body);
    await article.save();
    // Populate referenced fields for the response
    const populatedArticle = await Article.findById(article._id)
                                        .populate('author', 'name email')
                                        .populate('category', 'name slug')
                                        .populate('tags', 'name slug');
    return NextResponse.json(populatedArticle, { status: 201 });
  } catch (error: any) {
    console.error('Error creating article:', error);
    if (error.code === 11000) { // Duplicate key error (likely for slug)
        return NextResponse.json({ message: 'Article with this slug already exists.' }, { status: 409 });
    }
    return NextResponse.json({ message: 'Error creating article', error: error.message }, { status: 500 });
  }
}

// GET: Fetch all articles (with pagination and filtering options in a real app)
export async function GET(req: NextRequest) {
  await dbConnect();
  try {
    // Basic find for now. Add pagination, filtering, sorting later.
    // Example: /api/articles?status=published&category=tech&page=1&limit=10
    const { searchParams } = new URL(req.url);
    const page = parseInt(searchParams.get('page') || '1');
    const limit = parseInt(searchParams.get('limit') || '10');
    const status = searchParams.get('status');
    const categorySlug = searchParams.get('category'); // filter by category slug
    const tagSlug = searchParams.get('tag'); // filter by tag slug
    const authorId = searchParams.get('author');

    let query: any = {};
    if (status) query.status = status;
    if (authorId) query.author = authorId;

    if (categorySlug) {
        const category = await Category.findOne({ slug: categorySlug });
        if (category) query.category = category._id;
        else return NextResponse.json({ articles: [], totalPages: 0, currentPage: page }); // Category not found
    }

    if (tagSlug) {
        const tag = await Tag.findOne({ slug: tagSlug });
        if (tag) query.tags = { $in: [tag._id] };
        else return NextResponse.json({ articles: [], totalPages: 0, currentPage: page }); // Tag not found
    }

    const articles = await Article.find(query)
      .populate('author', 'name email') // Populate author with specific fields
      .populate('category', 'name slug') // Populate category
      .populate('tags', 'name slug') // Populate tags
      .sort({ publicationDate: -1, createdAt: -1 }) // Sort by publication date or creation date
      .skip((page - 1) * limit)
      .limit(limit);

    const totalArticles = await Article.countDocuments(query);
    const totalPages = Math.ceil(totalArticles / limit);

    return NextResponse.json({
        articles,
        totalPages,
        currentPage: page,
        totalArticles
    });
  } catch (error: any) {
    console.error('Error fetching articles:', error);
    return NextResponse.json({ message: 'Error fetching articles', error: error.message }, { status: 500 });
  }
}
